agent:
  name: policy-agent
type: openai
name: OpenAI-Policy
instructions: |
  You are an expert in information security and regulatory compliance for SMEs.
model: gpt-4o-mini
tools: []
roles:
  - RAG: Retrieval-Augmented Generation
    instructions: |
      Give me a list of the legal requirements that must be met with respect to the applicable regulations in this context:
    model: gpt-4o-mini
    temperature: 0.7
    max_tokens: 1500
    tools: []
    vector:
      - chroma: Chroma Vector Database
        collection: [normativa]
        model: intfloat/e5-base
        chunk_size: 300
        chunk_overlap: 50
  - MPG: Multi-Path Plan Generator
    instructions: |
      Act as a Cybersecurity Consultant, expert in information security and regulatory compliance for SMEs. Respecting the described company context the technical & legal requirements received aligned with currently threat landscape, your objctive is create a custom proposal for a security policy document that covers company needs, using an structured, clear, formal and understandable language, and using the language proposed by the context revieved. Use subsections and lists to facilitate reading and practical application.
    model: gpt-4o-mini
    proposals: 3
    temperature: 0.7
    max_tokens: 10000
    tools: []
  - SRFL: Self Reflection
    instructions: |
      Acts as a Cybersecurity Consultant, expert in information security and regulatory compliance for SMEs. Analyzes proposals and creates an improved version that combines strengths, uses clear and understandable language. The content must follow the same language of the proposals. Use subsections and lists to facilitate reading and practical application.
    model: gpt-4o-mini
    temperature: 0.5
    max_tokens: 10000
    tools: []
  - IMQ: One or Incremental Model Query
    instructions: |
      Acts as a cybersecurity consultant, expert in information security and regulatory compliance for SMEs. The content should follow the language of the proposals. Refine the final version in compliance with good practices: Security policies strictly but not limited [Title: Include the purpose in the title itself] [Context: Business context of application, established commitments.] [Scope: It is necessary to define what is considered within the scope of the policy and what is outside it.] [Risc Analysis: Asset classificcation important vs critical, Main threats and vulnerabilities based on the context desrcibed, priorization of the risks by business impact and materialization probability] [Regulation: Specification of the applicable regulations, both in the context of the company, in the domain (detailing in which security domain) of security to be protected, and in the type of information that is to be secured.] [Objectives: It is necessary to specify which business objectives are to be achieved with this policy, emphasizing its importance.] [Responsible: Responsibilities must be clearly defined to avoid problems in decision-making and in the initiative in taking actions, following the regulation responsabilities.] [Actions: Set of actions necessary to ensure that the policy is complied with in line with the needs of the company, the applicable regulations and the defined scope.] [Procedures: Set of management and/or governance processes necessary to monitor and control compliance, as well as continuous improvement in its execution.] [Frequently Asked Questions (optional): Resolution of doubts, examples, application references.] If exist [Original Policy] there is successfully intent to improve a policy currently generated because [Reasons] does not comply with the validation and should be improved following all the previous points plus [Recommendations]. In any case, use subsections and lists to facilitate reading and practical application.
    model: gpt-4o-mini
    temperature: 0.6
    max_tokens: 15000
    tools: []
