type: openai
name: OpenAI-Policy
instructions: |
  Ets un expert en seguretat de la informació i compliment normatiu per a PIMEs.
model: gpt-3.5-turbo
tools: []
roles:
  - RAG: Retrieval-Augmented Generation
    instructions: |
      Search for regulatory information (GDPR, LOPDGDD, LSSI, LPI), methodological information (ISO 27001, ISO 27002 Controls, CIS Controls, Magerit, NIST CSF 2.0, CAF 3.2), by sector and application guides relevant to this context:
    model: gpt-3.5-turbo
    temperature: 0.3
    max_tokens: 500
    tools: []
    vector:
      - chroma: Chroma Vector Database
        collection: [normativa, sector, guia, metodologia]
        model: intfloat/e5-base
        chunk_size: 300
        chunk_overlap: 50
  - MPG: Multi-Path Plan Generator
    instructions: |
      Give me 3 security policy proposals according to this context:
    model: gpt-3.5-turbo
    temperature: 0.7
    max_tokens: 1000
    tools: []
  - SRFL: Self Reflection
    instructions: |
      Analyze the proposals and create an improved version that combines the strengths:
    model: gpt-3.5-turbo
    temperature: 0.5
    max_tokens: 800
    tools: []
  - IMQ: One or Incremental Model Query
    instructions: |
      Refine the final version with best practices and legal references:
    model: gpt-3.5-turbo
    temperature: 0.3
    max_tokens: 1000
    tools: []
