agent:
  name: validator-agent
type: openai
name: OpenAI-Validator
instructions: |
  You are an expert in information security and regulatory compliance for SMEs.
model: gpt-4o-mini
tools: []
roles:
  - AWC: Agent Worker Compliance
    instructions: |
      Validate whether legal and regulatory references are coherent, follow each regulation step by step. Follow the language of the policy.
    model: gpt-4o-mini
    temperature: 0.3
    max_tokens: 2000
    prompt_template: |
      { instructions }

      ---

      Policy text:
      { prompt }

      Respond only with these validation results. STATUS:(accepted|review|reject), REASON:(justification) and RECOMMENDATIONS:(List of recommendations to improve).
  - AWL: Agent Worker Logic
    instructions: |
      Validate whether the policy structure is consistent with a security policy. Follow the language of the policy.
    model: gpt-4o-mini
    temperature: 0.3
    max_tokens: 1000
    prompt_template: |
      { instructions }

      ---

      Policy text:
      { prompt }

      Respond only with these validation results. STATUS:(accepted|review|reject), REASON:(justification) and RECOMMENDATIONS:(List of recommendations to improve).
  - AWT: Agent Worker Tone
    instructions: |
      Validates the appropriateness of language, tone, and clarity.  Follow the language of the policy.
    model: gpt-4o-mini
    temperature: 0.3
    max_tokens: 500
    prompt_template: |
      { instructions }

      ---

      Policy text:
      { prompt }

      Respond only with these validation results. STATUS:(accepted|review|reject), REASON:(justification) and RECOMMENDATIONS:(List of recommendations to improve).
  - EVA: Agent Evaluator
    instructions: |
      Once the validations have been collected, analyze and determine if the policy needs to be revised. Follow the language of the policy.
    model: gpt-4o-mini
    temperature: 0.5
    max_tokens: 3000
validation:
  rounds: 3
  consensus_threshold: 2
  vote_strategy: majority
