agent:
  name: validator-agent
type: openai
name: OpenAI-Validator
instructions: |
  You are an expert in information security and regulatory compliance for SMEs.
model: gpt-4o-mini
tools: []
prompt_template: |
  { instructions }

  ---

  Policy text:
  { prompt }

  Respond only with the validation result, justification and recommendations.
roles:
  - AWC: Agent Worker Compliance
    instructions: |
      Validate whether legal and regulatory references are coherent.
    model: gpt-4o-mini
    temperature: 0.3
    max_tokens: 500
  - AWL: Agent Worker Logic
    instructions: |
      Validate whether the policy structure is consistent with the plan and follows the base template.
    model: gpt-4o-mini
    temperature: 0.5
    max_tokens: 1000
  - AWT: Agent Worker Tone
    instructions: |
      Validates the appropriateness of language, tone, and clarity.
    model: gpt-4o-mini
    temperature: 0.3
    max_tokens: 500
  - EVA: Agent Evaluator
    instructions: |
      Once the validations have been collected, analyze and determine if the policy needs to be revised.
    model: gpt-4o-mini
    temperature: 0.5
    max_tokens: 1000
validation:
  rounds: 3
  consensus_threshold: 2
  vote_strategy: majority