answers: 
  - id: country 
    answer: Spain 
  - id: region 
    answer: Basque Country 
  - id: sector 
    answer: Legal services 
  - id: important_assets 
    answer: Court files, mails, legal documents. 
  - id: critical_assets 
    answer: Customer data and ongoing cases. 
  - id: current_security_operations 
    answer: File encryption, two-step authentication. 
  - id: methodology 
    answer: Partial application of ISO 27001 controls. 
  - id: generic 
    answer: Specific for legal confidentiality. 
  - id: need 
    answer: Avoid leaks and loss of sensitive data.